name: 'publish docs'

on:
  push:
    branches:
      - main
      - modify-actions
  
jobs:
  publish_sphinx_docs:
    name: Publish Sphinx Docs
    runs-on: ubuntu-latest
    steps:
    - uses: neuroinformatics-unit/actions/publish_sphinx_docs@add-docs-workflows
